[package]
name = "dist_lock"
version = "0.0.1"
authors = ["chenglong.wang <tiny.wcl@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
chrono = "0.4.26"
thiserror = "1.0.44"
redis = { version = "0.23.0", optional = true }
tokio = { version = "1.29.1", features = ["macros"], optional = true }
async-trait = "0.1.72"
gethostname = "0.4.3"
futures = "0.3.28"

[features]
default = ["redis_tokio_provider"]
redis_tokio_provider = ["redis/tokio-comp", "tokio"]
